dist: bionic
language: node_js
node_js:
  - "12"
sudo: required

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi

branches:
  only:
    - master
install: true
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: "Prepare Dependencies"
      name: "Prepare Dependencies"
      script:
        - npm install
    - stage: "Lint/Test"
      name: "Lint"
      script:
        - npm run lint
    - stage: "Unit/Test"
      name: "Unit Test"
      script:
        - npm run test
    - stage: "E2E/Test"
      name: "E2E"
      script:
        - npm list
        - npm run e2e
