dist: bionic
language: node_js
node_js:
  - "12"
sudo: required

services:
  - xvfb

branches:
  only:
    - master
install: true
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: "Prepare Dependencies"
      name: "Prepare Dependencies"
      script:
        - npm install
    - stage: "Lint/Test"
      name: "Lint"
      script:
        - npm run lint
    - stage: "Unit/Test"
      name: "Unit Test"
      script:
        - npm run test
    - stage: "E2E/Test"
      name: "E2E"
      script:
        - npm run e2e
