language: node_js
node_js:
  - "8"
sudo: required

branches:
  only:
    - master
install: true
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: "Prepare Dependencies"
      name: "Prepare Dependencies"
      script:
        - npm install
        - npm update
    - stage: "Lint/Test"
      name: "Lint"
      script:
        - npm run lint
