language: node_js

node_js:
  - "12"
sudo: required

branches:
  only:
    - master
install: true
cache:
  directories:
    - node_modules
    
jobs:
  include:
    - stage: Mac Setup and Tests
      os: osx
      name: "Prepare Dependencies"
      script:
        - npm install
        - npm update
    - <<: *Mac-Setup
      os: osx
      name: "Lint"
      script:
        - npm run lint
    - <<: *Mac-Setup
      os: osx
      name: "Jasmine"
      script:
        - npm run test

    - stage: Linux Setup
      os: linux
      name: "Prepare Dependencies"
      script:
        - npm install
        - npm update
    - <<: *Linux-Setup
      os: linux
      name: "Lint"
      script:
        - npm run lint
    - <<: *Linux-Setup
      os: linux
      name: "Jasmine"
      script:
        - npm run test
