language: node_js

node_js:
  - "12"
sudo: required

branches:
  only:
    - master
    - graphql-migration
install: true
cache:
  directories:
    - node_modules
    
jobs:
  include:
    - stage: Mac Setup and Tests
      os: osx
      name: "Prepare Dependencies"
      script:
        - npm install
        - npm update
    - <<: *Mac-Setup-and-Tests
      os: osx
      name: "Build"
      script:
        - npm run electron:mac
    - <<: *Mac-Setup-and-Tests
      os: osx
      name: "Lint"
      script:
        - npm run lint
    - <<: *Mac-Setup-and-Tests
      os: osx
      name: "Jasmine"
      script:
        - npm run test

    - stage: Linux Setup and Tests 
      os: linux
      name: "Prepare Dependencies"
      script:
        - npm install
        - npm update
    - <<: *Linux-Setup-and-Tests
      os: linux
      name: "Build"
      script:
        - npm run electron:linux
    - <<: *Linux-Setup-and-Tests
      os: linux
      name: "Lint"
      script:
        - npm run lint
    - <<: *Linux-Setup-and-Tests
      os: linux
      name: "Jasmine"
      script:
        - npm run test
