# The purpose of this workflow file is to generate
# a code coverage report from Codecov on new
# pushes and pull requests to the master branch

name: Get Code Coverage Report

on:
  push:
    branches: [master, release]
  pull_request:
    branches: [master, release]

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test -- "--code-coverage"
      - uses: codecov/codecov-action@v1
        with:
          directory: ./tests/coverage
